# Copyright 2026 Mantas Jonas Marcinkevičius
# Licensed under the Apache License, Version 2.0 (the "License");

import os
import configparser

class TranslationManager:
    def __init__(self):
        self.config = configparser.ConfigParser()
        self.config_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'config.ini')
        self.lang = 'en'
        self.load_config()
        
        # Translation Dictionary: Professional, non-pompous English ('en') and Lithuanian ('lt')
        self.translations = {
            'en': {
                # General Application Info
                'app_title': 'CeraMIS - Ceramic Microstructure and Impedance System',
                'author': 'Author',
                'select_file_btn': '📂 Select File...',
                'no_file_selected': 'No file selected',
                'load_error_title': 'Error reading file',
                'load_error_msg': 'Error: {}',
                'load_success_title': 'Success',
                'load_success_msg': 'Successfully loaded spectrum for {} temperatures.',
                'loading_default_project': 'Loading default dearEIS project...',
                
                # Main Tabs
                'tab_eis': 'EIS Analysis',
                'tab_arc': 'Arc Width Analysis',
                'tab_arr': 'Arrhenius Analysis',
                'tab_drt': 'DRT Analysis',
                'tab_fit': 'Circuit Modeling',
                'tab_sem': 'SEM AI Analysis',
                'tab_sem_stats': '📊 SEM Statistics',
                'tab_crystal': '💎 3D Crystal',
                'tab_settings': '⚙️ Settings',
                
                # Settings Tab
                'appearance_settings': 'Appearance & Layout',
                'language_settings': 'Language / Kalba',
                'language_label': 'Select Language (Needs Restart):',
                'restart_required_lang': 'Language changed. Please restart CeraMIS to apply changes.',
                
                # Paths Settings
                'paths_settings': 'Default Paths / Files',
                'default_eis_file': 'Default EIS File:',
                'default_deareis_file': 'Default dearEIS File:',
                'default_sem_folder': 'Default SEM Photos Folder:',
                'default_sem_stats_folder': 'Default SEM Stats Folder:',
                'browse_btn': 'Browse...',
                
                # EIS Tab Config
                'graph_matrix_title': 'Graph Layout (3x3 Matrix)',
                'sample_geometry_title': 'Sample Geometry',
                'thickness_label': 'Thickness L (mm):',
                'area_label': 'Area A (mm²):',
                'normalized_checkbox': 'Data already normalized (Ω·m)',
                'gui_scale_label': 'GUI Scale (Needs Restart):',
                'restart_required_scale': 'GUI Scale changed. Please restart CeraMIS to apply changes.',
                
                'temp_selection_title': 'Temperature Selection and Range',
                'select_all_btn': 'Select All',
                'deselect_all_btn': 'Deselect All',
                'temp_range_title': 'Temperature Range (K)',
                'freq_range_title': 'Frequency Range (Hz)',
                'from_label': 'From:',
                'to_label': 'To:',
                'select_btn': 'Select',
                'invalid_temp_range': 'Please enter valid temperatures!',
                
                # EIS Buttons
                'analyze_spectra_btn': '📈 Analyze Spectra',
                '3d_analysis_btn': '🚀 3D Analysis',
                'fast_3d_btn': '⚡ High-Performance 3D Plot (GPU)',
                'custom_plot_btn': '🗺️ Custom Plot',
                'export_excel_btn': '📊 Export to Excel (.xlsx)',
                'export_zview_btn': '📂 Export ZView (.z)',
                
                # Circuit Modeling
                'circuit_modeling_title': 'Circuit Modeling',
                'circuit_modeling_desc': 'Select circuit type and click \'Fit Model\'.',
                'fit_btn': 'Fit Model',
                'fit_success': 'Model fitted successfully!',
                
                # Arc Width Tab
                'arc_width_title': 'Nyquist Arc Width & Resistance Calculation',
                'arc_width_desc': 'Calculates the Nyquist plot arc width and real-axis resistance.',
                'calc_arc_btn': '📏 Calculate Arc Width (R)',
                
                # SEM AI Tab
                'sem_ai_title': 'SEM Microstructure AI Analysis',
                'sem_ai_desc': 'Uses Segment Anything Model (SAM) for automatic grain segmentation\nin SEM micrographs and extracts 2D+3D morphological statistics\n(diameter, circularity, roughness Ra, fracture topology index).',
                'run_sem_btn': '🔬 Run SEM AI Analyzer',
                
                # 3D Crystal Tab
                'crystal_title': 'LLTO Crystal Structure (3D)',
                'crystal_desc': 'Interactive 3D visualization of the LLTO perovskite structure.\nSupports real-time Li+ ion hop animation, stoichiometry config,\nand Cubic/Tetragonal phase switching.',
                'run_crystal_btn': '💎 Launch 3D Crystal Viewer',
                
                # DRT Tab
                'drt_project_section': 'DearEIS Project File (shared with Arrhenius tab)',
                'refresh_drt_btn': '🔄 Refresh Datasets from Project',
                'drt_select_temp': 'Select Temperature (Dataset)',
                'drt_limits': 'Peak Integration Bounds (Optional)',
                'drt_results': 'Results',
                'analyze_drt_btn': '📈 Analyze and Plot DRT',
                'plot_3d_drt_btn': '🗺️ Plot 3D DRT (T vs f)',
                'drt_no_project': 'Please load a project in the Arrhenius tab first.',
                'drt_found_datasets': 'Found datasets with DRT results: {}',
                'drt_no_datasets': 'No DRT results found in project. Please perform DRT calculations in dearEIS.',
                'drt_no_selected_ds': 'Please select a dataset.',
                'drt_missing_data': 'Dataset \'{}\' has no DRT data.',
                'drt_invalid_bounds': 'Invalid tau bounds.',
                'drt_few_points': 'Too few points in the specified range.',
                
                # DRT Popup & Peaks
                'drt_popup_title': 'DRT Analysis - {}',
                'drt_mark_info': 'Mark a peak region on the chart (drag a rectangle)',
                'drt_save_peak': '➕ Save Peak',
                'drt_clear_peaks': '🧹 Clear All',
                'drt_spectrum_label': 'DRT Spectrum',
                'drt_current_peak': 'Current Selection',
                'drt_saved_peak_legend': 'Peak {}: {}={:.3f} {}, C={:.2E} F',
                
                # Arrhenius Tab UI (Localised in arrhenius_module)
                'arr_project_section': 'DearEIS Project File (.json)',
                'arr_load_btn': '📂 Load dearEIS Project...',
                'arr_save_btn': '💾 Save Project Changes',
                'arr_component_sel': 'Resistance Component Selection for Arrhenius Fit',
                'arr_fit_idx': 'Fit Instance Index:',
                'arr_results_title': 'Arrhenius Activation Energy Results',
                'arr_extrapolate_title': 'Conductivity Extrapolation',
                'arr_temp_target': 'Target Temp (°C):',
                'arr_extrapolate_btn': '🧮 Extrapolate',
                'arr_plot_btn': '📈 Plot Arrhenius Graph',
                'arr_export_btn': '📊 Export Data to CSV',
                'arr_select_all': 'Select All Points',
                'arr_deselect_all': 'Deselect All Points',
                'arr_saved_lines_section': 'Saved Arrhenius Regressions',
                'arr_save_line_btn': '➕ Save Regression Line',
                'arr_clear_lines_btn': '🧹 Clear Saved Lines',
                'arr_point_details': 'Selected Point Details',
                
                # Messages & Warnings
                'msg_warning': 'Warning',
                'msg_error': 'Error',
                'msg_success': 'Success',
                'msg_info': 'Information',
                'no_project_loaded': 'No project loaded.',
                'error_loading_proj': 'Error loading project:\n{}',
                'proj_loaded_success': 'Successfully loaded project with {} datasets.',
                'proj_saved_success': 'Project changes saved successfully to {}!',
                
                # Graphic Names in Plot Selector Window
                'window_bode_title': 'CeraMIS - Bode Analysis & Fitting',
                'window_plots_title': 'CeraMIS - Impedance Spectroscopy and Microstructure System',
                'axis_frequency': 'Frequency f, Hz',
                'axis_real_z': "Real Impedance Z', \u03a9",
                'axis_imag_z': "-Imaginary Impedance -Z'', \u03a9",
                'axis_real_eps': "Real Permittivity \u03b5'",
                'axis_imag_eps': "Imaginary Permittivity \u03b5''",
                'axis_conductivity': "Real Conductivity \u03c3', S/cm",
                'axis_imag_m': "Imaginary Modulus M''",
                'axis_tan_delta': 'Loss Tangent tan \u03b4',
                'axis_phase': 'Phase Angle -\u0398, deg',
                'axis_abs_z': 'Impedance Magnitude |Z|, \u03a9',
                'nyquist_title': 'Nyquist Plot',
                'bode_title': 'Bode Plot',
                'cole_cole_title': 'Cole-Cole Plot',
                
                # Extra
                'point_info_label': 'Left-click a point to analyze | Double-right-click to edit charts',
                'saved_regression': 'Saved',
                'active_regression': 'Active',

                # SEM Statistics Tab
                'sem_stats_header': '📊 LLTO SEM Grain Size Statistical Analysis',
                'sem_stats_header_desc': 'Combines up to 10 Excel files of grain data and performs full bimodal statistical analysis',
                'sem_stats_excel_files_title': 'Excel Files (up to 10)',
                'sem_stats_add_files_btn': '➕ Add Files...',
                'sem_stats_remove_btn': '🗑️ Remove Selected',
                'sem_stats_clear_all_btn': '🧹 Clear All',
                'sem_stats_col_mapping_title': 'Column Mapping',
                'sem_stats_col_diameter': 'Equiv. Diameter (µm):',
                'sem_stats_col_area': 'Area (µm²):',
                'sem_stats_col_ff': 'Sphericity (Form Factor):',
                'sem_stats_col_aspect': 'Anisotropy (Aspect Ratio):',
                'sem_stats_col_perimeter': 'Perimeter (µm):',
                'sem_stats_col_area_3d': '3D Area (µm²):',
                'sem_stats_col_roughness': 'Surface Roughness Ra (nm):',
                'sem_stats_auto_detect_btn': '🔍 Auto-Detect Columns',
                'sem_stats_run_btn': '▶ START ANALYSIS',
                'sem_stats_plot_btn': '📈 Bimodal Histogram + KDE',
                'sem_stats_export_btn': '💾 Export Results (.xlsx)',
                'sem_stats_status_init': 'Load Excel files and click Start Analysis.',
                'sem_stats_results_title': 'Statistical Results',
                'sem_stats_tbl_param': 'Parameter',
                'sem_stats_tbl_mean_std': 'Mean ± Std. Dev.',
                'sem_stats_tbl_units': 'Units',
                'sem_stats_select_files_title': 'Select SEM Data Files (Excel or CSV)',
                'sem_stats_filetype_data': 'Data Files',
                'sem_stats_filetype_excel': 'Excel',
                'sem_stats_filetype_csv': 'CSV',
                'sem_stats_filetype_all': 'All Files',
                'sem_stats_max_files_warning': 'A maximum of 10 files can be loaded.',
                'sem_stats_status_cleared': 'Cleared. Please load files.',
                'sem_stats_load_errors_title': 'Loading Errors',
                'sem_stats_status_loaded': 'Loaded {num} files. Check column mapping and click START ANALYSIS.',
                'sem_stats_status_detected': 'Columns auto-detected. Verify mapping and click START ANALYSIS.',
                'sem_stats_no_files_warning': 'Please load Excel files first.',
                'sem_stats_param_gb_density': 'Grain Boundary Density',
                'sem_stats_param_roughness_macro': 'Surface Roughness Ra (Global)',
                'sem_stats_param_fracture': 'Fracture Topology Index',
                'sem_stats_genitive_diameter': 'Equivalent Diameter',
                'sem_stats_genitive_area': 'Grain Area',
                'sem_stats_genitive_ff': 'Sphericity',
                'sem_stats_genitive_aspect': 'Anisotropy',
                'sem_stats_genitive_perimeter': 'Perimeter',
                'sem_stats_genitive_area_3d': '3D Area',
                'sem_stats_genitive_roughness': 'Ra Roughness',
                'sem_stats_axis_diameter': 'Equivalent Diameter',
                'sem_stats_axis_area': 'Area',
                'sem_stats_axis_ff': 'Sphericity',
                'sem_stats_axis_aspect': 'Anisotropy',
                'sem_stats_axis_perimeter': 'Perimeter',
                'sem_stats_axis_area_3d': '3D Area',
                'sem_stats_axis_roughness': 'Ra Roughness',
                'sem_stats_param_fracture_type': 'Fracture Type (Dominant)',
                'sem_stats_status_completed': '✅ Analysis finished ({num} files). Grains: {micro}. Global parameters: {macro}.',
                'sem_stats_tree_hdr_micro': '── MICRO Parameters (Global Array) ──',
                'sem_stats_tree_hdr_macro': '── MACRO Parameters (Mean per File) ──',
                'sem_stats_histogram_warning': 'Please run the analysis first (requires diameter or area data).',
                'sem_stats_histogram_win_title': 'Grain Size Distribution Analysis',
                'sem_stats_select_param': 'Select parameter: ',
                'sem_stats_peaks_legend': 'Peaks: {peaks} {unit}',
                'sem_stats_mean_legend': 'Mean: {mean:.3f} ± {std:.3f} {unit}',
                'sem_stats_axis_density': 'Probability Density',
                'sem_stats_plot_title': 'LLTO Grain {label} Distribution (N={num})',
                'sem_stats_radio_diameter': 'Diameter',
                'sem_stats_radio_area': 'Area',
                'sem_stats_radio_ff': 'Sphericity',
                'sem_stats_radio_aspect': 'Anisotropy',
                'sem_stats_radio_perimeter': 'Perimeter',
                'sem_stats_radio_area_3d': '3D Area',
                'sem_stats_radio_roughness': 'Roughness Ra',
                'sem_stats_no_results_warning': 'Please run the analysis first.',
                'sem_stats_export_title': 'Save SEM Statistics',
                'sem_stats_col_mean': 'Mean',
                'sem_stats_col_std': 'Std. Dev.',
                'sem_stats_col_type': 'Type',
                'sem_stats_sheet_stats': 'Statistics',
                'sem_stats_sheet_combined': 'Combined_Data',
                'sem_stats_export_success_msg': 'Results saved successfully:\n{}',
                'sem_stats_export_error_msg': 'Failed to save file:\n{}',

                # Arc Width Analysis
                'arc_no_data': 'Please load data first!',
                'arc_all_selected': 'All Selected',
                'arc_window_title': 'CeraMIS - Arc Width Analysis (Rectangle Selection)',
                'arc_sidebar_title': 'ARC WIDTH ANALYSIS',
                'arc_desc_usage': 'Usage:\n1. Right-click and drag a rectangle around the desired arc.\n2. Click [Lock Arc] or press \'S\' to save the arc.\n3. Drag around another arc and repeat.',
                'arc_temp_selection': 'Temperature Selection:',
                'arc_locked_results_title': 'Locked Results:',
                'arc_no_locked_arcs': 'No locked arcs yet.\n',
                'arc_no_points_selected': 'No points in selected region!',
                'arc_results_label': 'Results:\n',
                'arc_and_more_label': '\n... and {} more',
                'axis_real_z_norm': "Z', \u03a9\u00b7m",
                'axis_imag_z_norm': "-Z'', \u03a9\u00b7m",
                'arc_plot_instruction': 'Use right click to drag a rectangle around an arc\nLocked arcs: {}',
                'arc_sidebar_arc_info': 'Arc #{idx} ({temp} K):\n',
                'arc_please_select_first': 'Please drag a rectangle around an arc first!',
                'arc_locked_success_title': 'Arc successfully locked! Select another one.\nLocked arcs: {}',
                'arc_no_arcs_export': 'No locked arcs to export!',
                'arc_export_save_title': 'Save Arc Analysis Results',
                'arc_excel_sheet_title': 'Arc Results',
                'arc_col_index': 'Arc Index',
                'arc_col_temp': 'Temperature',
                'arc_col_resistance': 'Resistance R',
                'arc_col_n': 'CPE Exponent n',
                'arc_col_q': 'CPE Capacitance Q',
                'arc_col_ceq': 'Equivalent Capacitance C_eq',
                'arc_col_x1': 'Intercept X1',
                'arc_col_x2': 'Intercept X2',
                'arc_col_chi2': 'Chi-Square (Chi²)',
                'arc_item_prefix': 'Arc #{}',
                'arc_export_success': 'Origin-compatible data successfully exported to:\n{}',
                'arc_export_error': 'Failed to export to Excel:\n{}',
                'arc_import_title': 'Import Arc Analysis Results',
                'arc_import_structure_error': 'Invalid file structure! Could not find required arc columns.',
                'arc_import_dialog_title': 'Import Data',
                'arc_import_confirm_clear': 'You already have locked arcs. Do you want to clear them before importing?\nSelecting \'Yes\' will clear existing arcs.\nSelecting \'No\' will append the imported arcs.\nSelecting \'Cancel\' will abort the action.',
                'arc_import_success_msg': 'Successfully imported {} arcs.',
                'arc_import_error_msg': 'Failed to read Excel file:\n{}',
                'arc_lock_btn': '🔒 Lock Arc (S)',
                'arc_clear_btn': '🧹 Clear Locked (C)',
                'arc_import_btn': '📂 Import from Excel',
                'arc_export_btn': '📊 Export to Excel',

                # DRT Tab Additions
                'drt_tau_min': 'tau min (s):',
                'drt_tau_max': 'tau max (s):',
                'drt_auto_bounds_placeholder': '(leave empty for automatic detection)',
                'drt_no_auto_peak': 'No peak found automatically. Please specify bounds manually.',
                'drt_no_data_in_project': 'No DRT data found in project.',
                'drt_3d_map_title': '3D DRT Map',
                'drt_3d_temp_axis': 'Temperature, K',
                'drt_3d_gamma_axis': '\u03b3(ln \u03c4), \u03a9',
                'drt_3d_title': 'DRT Distribution vs Temperature and Frequency',
                'drt_analysis_title': 'DRT Analysis: {}',

                # 3D Crystal Viewer
                'crystal_view_title': '🔷 LLTO Crystal Structure\n3D Visualization',
                'crystal_phase_label': 'Crystallographic phase:',
                'crystal_phase_cubic': 'Cubic',
                'crystal_phase_tetragonal': 'Tetragonal',
                'crystal_phase_orthorhombic': 'Orthorhombic',
                'crystal_phase_monoclinic': 'Monoclinic',
                'crystal_phase_twinned': 'Twinned Domains',
                'crystal_phase_amorphous': 'Amorphous',
                'crystal_phase_rp': 'Ruddlesden-Popper',
                'crystal_cell_label': 'Supercell size:',
                'crystal_show_boundary': 'Show domain boundary',
                'crystal_show_windows': 'Show oxygen windows',
                'crystal_show_radii': 'Show ionic radii',
                'crystal_stoichiometry': 'Stoichiometry',
                'crystal_apply_btn': 'Apply Phase & Stoichiometry',
                'crystal_temp_label': 'Temperature: {} K',
                'crystal_tilt_label': 'Octahedron tilt: {}°',
                'crystal_tilt_format': 'Octahedron tilt: {}° (Ti-O-Ti: {}°)',
                'crystal_jump_start': '▶ Start Li Hop Animation',
                'crystal_jump_stop': '⏸ Stop Jump Animation',
                'crystal_jump_field_active': '▶ Start Hop (Field Active)',
                'crystal_no_pairs': 'No adjacent Li-Vacancy pairs found for animation.',
                'crystal_field_check': 'Enable electric field effect',
                'crystal_field_group': '⚡ Electric Field',
                'crystal_white_bg': 'White Background',
                'crystal_export_png': '📷 Export PNG',
                'crystal_save_png_title': 'Save PNG',
                'crystal_png_filetype': 'PNG Image (*.png)',
                'crystal_domain_boundary_label': 'Domain boundary',
                'crystal_atom_La': 'La',
                'crystal_atom_Li': 'Li',
                'crystal_atom_Ti': 'Ti',
                'crystal_atom_O': 'O',
                'crystal_atom_Vac': 'Vacancy',

                # Meta-data & Graph keys
                'meta_z_real_f': "Real Impedance Z' vs f",
                'meta_z_imag_f': "-Imaginary Impedance -Z'' vs f",
                'meta_eps_real_f': "Real Permittivity \u03b5' vs f",
                'meta_eps_imag_f': "Imaginary Permittivity \u03b5'' vs f",
                'meta_sigma_f': "Real Conductivity \u03c3' vs f",
                'meta_m_imag_f': "Imaginary Modulus M'' vs f",
                'meta_tan_delta_f': "Loss Tangent tan \u03b4 vs f",
                'meta_z_real_imag_f': "Real and Imaginary Impedance vs f",
                'meta_z_real_imag_label': "Real Z' and Imaginary -Z''",
                'meta_abs_z_f': "Impedance Magnitude |Z| vs f",
                'plot_open_error': "Error opening plot: {}",
                'label_temp_k': "Temperature (K)",
                'title_edit_export_graph': "Edit & Export Graph Data",
                'btn_updated_success': "Successfully updated chart settings!",
                'btn_update': "🔄 Update Chart",
                'title_export_graph': "Export Graph Data",
                'btn_exported_success': "Data exported successfully!",
                'btn_export_dots': "📊 Export Points to Excel",
                'btn_copied_success': "Data successfully copied to clipboard!",
                'btn_copy_clipboard': "📋 Copy to Clipboard",
                'label_none': "None",
                'btn_plot': "📈 Plot",

                # 3D PyVista Plot Titles
                'title_3d_nyquist_bode_spiral': "3D Nyquist-Bode Spiral",
                'title_nyquist_evolution': "Nyquist Evolution vs Temperature",
                'title_cole_cole_3d': "Cole-Cole 3D (\u03b5' vs \u03b5'' vs T)",
                'title_phase_angle_3d': "Phase Angle 3D (-\u0398)",
                'title_3d_ac_conductivity': "3D AC Conductivity Surface",
                'title_electric_modulus_surface': "Electric Modulus Surface (M'')",
                'title_pseudo_drt_relief': "Pseudo-DRT Temperature Relief",
                'title_conductivity_map': "Conductivity Map (1000/T)",
                'title_norm_z_surface': "Normalized Z'' Surface",
                'title_norm_m_surface': "Normalized M'' Surface",

                # SAM interactive UI keys
                'sam_palette': "Color Palette:",
                'sam_smooth': "Boundary Smoothing:",
                'sam_height': "Relief Height Scale:",
                'sam_opacity': "3D Mesh Opacity:",
                'sam_btn_update': "🔄 Update 3D Model",
                'sam_status_calc': "Grain stats: {num} grains, GB density = {density:.4f} \u00b5m\u207b\u00b9, Ra = {ra:.2f} nm, Fracture index = {frac:.3f}",
                'sam_btn_save_png': "📷 Save 3D Render as PNG",
                'sam_btn_export_xlsx': "📊 Export Grain Details to Excel",
                'sam_btn_repeat': "🔄 Recalculate Statistics",
                'sam_btn_roi': "✂ Change Region (ROI)",
                'sam_btn_save_png_short': "📷 Save PNG",
                'sam_status_found': "Found {num} grains",
                'sam_manual_header': "🔬 SEM AI Manual Measurement Mode",
                'sam_lbl_param': "Parameter",
                'sam_lbl_val': "Value",

                # Arrhenius and layout missing keys
                'arr_status_waiting': "Waiting for project...",
                'arr_load_proj_placeholder': "(load project)",
                'arr_click_point_info': "Click a point for details",
                'arr_browse_btn': "Browse...",
                'arr_fit_select_title': "Fitting Result Selection",
                'arr_fit_last': "Last",
                'arr_fit_first': "First",
                'arr_fit_index_label': "By Index:",
                'arr_select_proj_title': "Select dearEIS Project",
                'arr_proj_filetype': "dearEIS Project",
                'filetype_all': "All files",
                'arr_proj_loaded': "Project loaded. Datasets: {}",
                'arr_no_fits': "(no fitting results)",
                'arr_and_more': "  ... and {} more",
                'arr_fit_results_header': "Fitting results (first dataset):\n",
                'arr_proj_loaded_auto': "Project loaded automatically. Datasets: {}",
                'arr_select_point_or_reg': "Select a point or regression",
                'arr_invalid_temp': "Invalid temperature",
                'invalid_geometry': "Invalid geometry data in the main window.",
                'arr_no_data_found': "No suitable data found.",
                'arr_plot_title_r': "Arrhenius Plot ($R$=$R_{t}$+$R_{gr}$)",
                'arr_plot_title_prefix': "Arrhenius Plot",
                'arr_analysis_title': "Arrhenius Analysis",
                'arr_regression_label': "Regression:",
                'arr_plot_title_formula': "Arrhenius Plot",
                'arr_instructions': "🖱️ Drag selection box (left/right click) to select/deselect points. 🎯 Click a point for info.",
                'arr_plot_ready': "Plot ready. Points: {}",
                'arr_current_pts': "Current",
                'arr_select_pts_for_reg': "(select points for regression)",
                'arr_need_2_points': "At least 2 selected points are required to save a regression line.",
                'arr_source_data_point': "Data Point",
                'arr_source_line': "Line",
                'arr_source_active': "Active Regression",
                'arr_point_label': "Point",
                'arr_selected_point_status': "Selected point {temp_k:.1f} K ({source}). {name} = {val} {unit} | \u03c3 = {sigma} S/cm",
                'arr_all_deselected': "All points deselected.",
                'arr_original_file_missing': "Original project file not found.",
                'arr_proj_updated_saved': "Project updated and saved successfully.",
                'arr_error_saving_proj': "Error saving project:\n{}",
                'arr_save_csv_title': "Save CSV",
                'arr_csv_filetype': "CSV File",
                'arr_csv_saved': "CSV saved to:\n{}",
                'drt_results_placeholder': "(select dataset and bounds)",
                'filetype_supported': "Supported files",
                'filetype_txt': "Text files",
                'filetype_zview': "ZView files",
                'filetype_excel': "Excel files",
                'sem_settings_title': "SEM AI Settings",
                'sam_model_version_label': "SAM Model Version:",
                'sam_window_title_3d': "SAM 3D Relief - Interactive Analysis",
                'sam_window_title_manual': "SAM Manual Adjustment",
                'sam_scale_win_title': "Scale",
                'sam_units_vnt': "pcs.",
                'sam_scale_prompt': "Enter the length of the marked scale line in micrometers (µm):",
                'sam_step1_title': "STEP 1: Set the scale!\nClick on the start of the scale line, then on the end.",
                'sam_step2_title': "STEP 2: Select the processing region!\nDrag a rectangle with the mouse over the desired region.\nPress 'Enter' when done.",
                'sam_manual_title_format': "Grains found in the processed region: {len_masks}",
                'sam_manual_info_bar': "MANUAL PROCESSING  |  [J] Merge  |  [D] Delete  |  [S] Split  |  [ESC] Exit",
                'sam_select_image_title': "Select SEM image for analysis",
                'sam_image_filetype_desc': "Images",
                'sam_merge_warning': "Select at least 2 grains for merging!",
                'sam_split_prompt': "Splitting grain {idx}. Mark two points in the center of the new parts.",
                'sam_export_grain_sheet': "Grain Details",
                'sam_stats_calculated': "Calculated Parameters:",
                'sam_export_success': "Parameters successfully exported!",
                'sam_export_error': "Failed to export parameters!",
                'sam_stat_algorithm': "Algorithm",
                'sam_stat_count': "Grain Count",
                'sam_stat_mean_diam': "Mean Diameter",
                'sam_stat_min_diam': "Min Diameter",
                'sam_stat_max_diam': "Max Diameter",
                'sam_stat_mean_area': "Mean Area",
                'sam_stat_min_area': "Min Area",
                'sam_stat_max_area': "Max Area",
                'sam_stat_sphericity': "Mean Sphericity",
                'sam_stat_aspect': "Mean Anisotropy",
                'sam_stat_gb_density': "GB Density",
                'sam_stat_roughness': "Mean Ra",
                'sam_stat_fracture_idx': "Fracture Index",
                'sam_stat_fracture_type': "Fracture Type",
                'fracture_Stipriai_Intergranuliarinis': "Strongly Intergranular",
                'fracture_Transgranuliarinis': "Transgranular",
                'fracture_Mišrus': "Mixed",
                'script_not_found': "Script {} not found.",
                'axis_log_f': "log(f), Hz",
                'axis_real_eps_unit': "ε', arb. units",
                'axis_imag_eps_unit': "ε'', arb. units",
                'axis_phase_angle_short': "-Θ, °",
                'axis_conductivity_surface': "log(σ'), S/m",
                'axis_imag_m_unit': "M'', arb. units",
                'axis_pseudo_drt_value': "-dZ'/d(log f)",
                'axis_inv_temp': "1000/T, K⁻¹",
                'axis_norm_z_spec': "Z''/Z''max",
                'axis_norm_m_spec': "M''/M''max",
                'sam_status_recalculating': "⏳ Recalculating, please wait...",
                'sam_excel_stat_mean': "Mean",
                'sam_excel_stat_min': "Minimum",
                'sam_excel_stat_max': "Maximum",
                'sam_excel_stat_std': "Std. Dev.",
                'sam_excel_param': "Parameter",
                'sam_excel_value': "Value",
                'sam_excel_sheet': "Analysis",
                'sam_stat_mean_diam_col': "Mean Diameter",
                'sam_opac_percent': "Opacity: {}%",
                'sam_smooth_iter': "{} iter.",
                'sam_height_x': "{:.1f}x",
                'sam_open_3d_msg': "Opening 3D Window! You can rotate with mouse, zoom with scroll wheel."
            },
            'lt': {
                # General Application Info
                'app_title': 'CeraMIS - Keramikos Mikrostruktūros ir Impedanso Sistema',
                'author': 'Autorius',
                'select_file_btn': '📂 Pasirinkti failą...',
                'no_file_selected': 'Nepasirinktas joks failas',
                'load_error_title': 'Klaida skaitant failą',
                'load_error_msg': 'Klaida: {}',
                'load_success_title': 'Sėkmė',
                'load_success_msg': 'Sėkmingai nuskaityti {} temperatūrų spektrai.',
                'loading_default_project': 'Įkeliamas numatytasis dearEIS projektas...',
                
                # Main Tabs
                'tab_eis': 'EIS Analizė',
                'tab_arc': 'Lanko pločio analizė',
                'tab_arr': 'Arenijaus analizė',
                'tab_drt': 'DRT Analizė',
                'tab_fit': 'Modeliavimas',
                'tab_sem': 'SEM Analizė (AI)',
                'tab_sem_stats': '📊 SEM Statistika',
                'tab_crystal': '💎 3D Kristalas',
                'tab_settings': '⚙️ Nustatymai',
                
                # Settings Tab
                'appearance_settings': 'Išvaizda ir išdėstymas',
                'language_settings': 'Kalba / Language',
                'language_label': 'Pasirinkti kalbą (Reikia perkrauti):',
                'restart_required_lang': 'Kalba pakeista. Prašome paleisti CeraMIS iš naujo, kad pakeitimai įsigaliotų.',
                
                # Paths Settings
                'paths_settings': 'Numatytieji keliai ir failai',
                'default_eis_file': 'Numatytas EIS failas:',
                'default_deareis_file': 'Numatytas dearEIS failas:',
                'default_sem_folder': 'Numatytas SEM nuotraukų katalogas:',
                'default_sem_stats_folder': 'Numatytas SEM statistikos katalogas:',
                'browse_btn': 'Naršyti...',
                
                # EIS Tab Config
                'graph_matrix_title': 'Grafikų išdėstymas (3x3 matrica)',
                'sample_geometry_title': 'Bandinio geometrija',
                'thickness_label': 'Storis L (mm):',
                'area_label': 'Plotas A (mm²):',
                'normalized_checkbox': 'Duomenys jau normalizuoti (Ω·m)',
                'gui_scale_label': 'GUI Mastelis (Pakeitimams reikia perkrauti):',
                'restart_required_scale': 'GUI mastelis pakeistas. Prašome paleisti CeraMIS iš naujo, kad pakeitimai įsigaliotų.',
                
                'temp_selection_title': 'Temperatūrų žymėjimas ir diapazonas',
                'select_all_btn': 'Pažymėti viską',
                'deselect_all_btn': 'Atžymėti visus',
                'temp_range_title': 'Temperatūrų diapazonas (K)',
                'freq_range_title': 'Dažnių intervalas (Hz)',
                'from_label': 'Nuo:',
                'to_label': 'Iki:',
                'select_btn': 'Pasirinkti',
                'invalid_temp_range': 'Įveskite teisingas temperatūras!',
                
                # EIS Buttons
                'analyze_spectra_btn': '📈 Analizuoti spektrus',
                '3d_analysis_btn': '🚀 3D Analizė',
                'fast_3d_btn': '⚡ Greitaveikis 3D grafikas (GPU)',
                'custom_plot_btn': '🗺️ Individualus grafikas',
                'export_excel_btn': '📊 Eksportuoti į Excel (.xlsx)',
                'export_zview_btn': '📂 Eksportuoti ZView (.z)',
                
                # Circuit Modeling
                'circuit_modeling_title': 'Grandinės Modeliavimas',
                'circuit_modeling_desc': 'Pasirinkite grandinės tipą ir paspauskite \'Derinti modelį\'.',
                'fit_btn': 'Derinti modelį',
                'fit_success': 'Modelis priderintas sėkmingai!',
                
                # Arc Width Tab
                'arc_width_title': 'Lanko Pločio Skaičiavimas',
                'arc_width_desc': 'Skaičiuoja Naikvisto kreivės lanko plotį bei varžą.',
                'calc_arc_btn': '📏 Skaičiuoti lanko plotį (R)',
                
                # SEM AI Tab
                'sem_ai_title': 'SEM Mikrostruktūros Analizė (AI)',
                'sem_ai_desc': 'Naudoja SAM 2/3 (Segment Anything Model) automatiniam grūdelių segmentavimui\nSEM mikrografijose ir išgaunamą 2D+3D morfologinę statistiką\n(diametras, sferiškumas, šiurkštumas Ra, lūžio topologijos indeksas).',
                'run_sem_btn': '🔬 Paleisti SEM Analizę (AI)',
                
                # 3D Crystal Tab
                'crystal_title': 'LLTO Kristalų Struktūra (3D)',
                'crystal_desc': 'Interaktyvi 3D vizualizacija, skirta LLTO perovskito struktūrai.\nPalaikomas nepertraukiamas Li+ jonų šuolių animavimas,\nstechiometrijos konfigūravimas ir fazių (Cubic/Tetragonal) perjungimas.',
                'run_crystal_btn': '💎 Paleisti 3D Kristalų Vizualizaciją',
                
                # DRT Tab
                'drt_project_section': 'DearEIS projekto failas (bendras su Arenijaus skirtuku)',
                'refresh_drt_btn': '🔄 Atnaujinti datasetų sąrašą iš projekto',
                'drt_select_temp': 'Pasirinkite temperatūrą (Datasetą)',
                'drt_limits': 'Piko ribos integracijai (neprivaloma)',
                'drt_results': 'Rezultatai',
                'analyze_drt_btn': '📈 Analizuoti ir braižyti DRT',
                'plot_3d_drt_btn': '🗺️ Braižyti 3D DRT (T vs f)',
                'drt_no_project': 'Pirmiausia įkelkite projektą Arenijaus skirtuke.',
                'drt_found_datasets': 'Rasta datasetų su DRT rezultatais: {}',
                'drt_no_datasets': 'Projekte nerasta jokių DRT rezultatų. Atlikite DRT skaičiavimą dearEIS programoje.',
                'drt_no_selected_ds': 'Pasirinkite datasetą.',
                'drt_missing_data': 'Datasetas \'{}\' neturi DRT rezultatų dearEIS faile.',
                'drt_invalid_bounds': 'Neteisingi tau rėžiai.',
                'drt_few_points': 'Per mažai taškų nurodytame rėžyje.',
                
                # DRT Popup & Peaks
                'drt_popup_title': 'DRT Analizė - {}',
                'drt_mark_info': 'Pažymėkite piko sritį grafike (stačiakampiu)',
                'drt_save_peak': '➕ Išsaugoti piką',
                'drt_clear_peaks': '🧹 Išvalyti visus',
                'drt_spectrum_label': 'DRT spektras',
                'drt_current_peak': 'Dabartinis',
                'drt_saved_peak_legend': 'Pikas {}: {}={:.3f} {}, C={:.2E} F',
                
                # Arrhenius Tab UI
                'arr_project_section': 'DearEIS projekto failas (.json)',
                'arr_load_btn': '📂 Įkelti dearEIS projektą...',
                'arr_save_btn': '💾 Išsaugoti projekto pakeitimus',
                'arr_component_sel': 'Varžos komponento parinkimas Arenijaus regresijai',
                'arr_fit_idx': 'Fit derinimo indeksas:',
                'arr_results_title': 'Arenijaus aktyvacijos energijos rezultatai',
                'arr_extrapolate_title': 'Laidumo ekstrapoliacija',
                'arr_temp_target': 'Temperatūra (°C):',
                'arr_extrapolate_btn': '🧮 Ekstrapoliuoti',
                'arr_plot_btn': '📈 Braižyti Arenijaus grafiką',
                'arr_export_btn': '📊 Eksportuoti duomenis į CSV',
                'arr_select_all': 'Pažymėti visus taškus',
                'arr_deselect_all': 'Atžymėti visus taškus',
                'arr_saved_lines_section': 'Išsaugotos Arenijaus regresijos',
                'arr_save_line_btn': '➕ Išsaugoti regresijos tiesę',
                'arr_clear_lines_btn': '🧹 Išvalyti išsaugotas tieses',
                'arr_point_details': 'Pasirinkto taško informacija',
                
                # Messages & Warnings
                'msg_warning': 'Dėmesio',
                'msg_error': 'Klaida',
                'msg_success': 'Sėkmė',
                'msg_info': 'Informacija',
                'no_project_loaded': 'Nėra atidaryto projekto.',
                'error_loading_proj': 'Klaida atidarant projektą:\n{}',
                'proj_loaded_success': 'Sėkmingai įkeltas projektas su {} datasetų.',
                'proj_saved_success': 'Pakeitimai sėkmingai išsaugoti į {}!',
                
                # Graphic Names in Plot Selector Window
                'window_bode_title': 'CeraMIS - Bode analizė ir modeliavimas',
                'window_plots_title': 'CeraMIS – LLTO keramikos Mikrostruktūros ir Impedanso Analizės Sistema',
                'axis_frequency': 'Dažnis f, Hz',
                'axis_real_z': "Varžos realioji dalis Z', \u03a9",
                'axis_imag_z': "-Varžos tariamoji dalis -Z'', \u03a9",
                'axis_real_eps': "Skvarbos realioji dalis \u03b5'",
                'axis_imag_eps': "Skvarbos tariamoji dalis \u03b5''",
                'axis_conductivity': "Laidumo realioji dalis \u03c3', S/cm",
                'axis_imag_m': "Modulio tariamoji dalis M''",
                'axis_tan_delta': 'Nuostolių tangentas tan \u03b4',
                'axis_phase': 'Fazės kampas -\u0398, laipsniai',
                'axis_abs_z': 'Varžos modulis |Z|, \u03a9',
                'nyquist_title': 'Naikvisto grafikas',
                'bode_title': 'Bodo grafikas',
                'cole_cole_title': 'Cole-Cole grafikas',
                
                # Extra
                'point_info_label': 'Kairiuoju pelės mygtuku spauskite ant taško, kad jį pažymėtumėte analizei | Du kartus spauskite dešiniuoju pelės mygtuku, kad redaguotumėte grafiką',
                'saved_regression': 'Išsaugota',
                'active_regression': 'Aktyvi',

                # SEM Statistics Tab
                'sem_stats_header': '📊 LLTO SEM Grūdelių dydžio bendra statistinė analizė',
                'sem_stats_header_desc': 'Apjungia iki 10 Excel failų grūdelių duomenis ir atlieka pilną bimodalinę statistinę analizę',
                'sem_stats_excel_files_title': 'Excel failai (iki 10)',
                'sem_stats_add_files_btn': '➕ Pridėti failus...',
                'sem_stats_remove_btn': '🗑️ Pašalinti pažymėtus',
                'sem_stats_clear_all_btn': '🧹 Išvalyti viską',
                'sem_stats_col_mapping_title': 'Stulpelių priskyrimas',
                'sem_stats_col_diameter': 'Ekv. diametras, µm:',
                'sem_stats_col_area': 'Plotas, µm²:',
                'sem_stats_col_ff': 'Sferiškumas (Form factor):',
                'sem_stats_col_aspect': 'Anizotropija (Aspect):',
                'sem_stats_col_perimeter': 'Perimetras, µm:',
                'sem_stats_col_area_3d': '3D Plotas, µm²:',
                'sem_stats_col_roughness': 'Pavirš. šiurkštumas Ra (mikro):',
                'sem_stats_auto_detect_btn': '🔍 Aptikti stulpelius automatiškai',
                'sem_stats_run_btn': '▶ PRADĖTI ANALIZĘ',
                'sem_stats_plot_btn': '📈 Bimodalė histograma + KDE',
                'sem_stats_export_btn': '💾 Eksportuoti rezultatus (.xlsx)',
                'sem_stats_status_init': 'Įkelkite Excel failus ir pradėkite analizę.',
                'sem_stats_results_title': 'Statistikos rezultatai',
                'sem_stats_tbl_param': 'Parametras',
                'sem_stats_tbl_mean_std': 'Vidurkis ± St.nuokrypis',
                'sem_stats_tbl_units': 'Vienetai',
                'sem_stats_select_files_title': 'Pasirinkite SEM duomenų failus (Excel arba CSV)',
                'sem_stats_filetype_data': 'Duomenų failai',
                'sem_stats_filetype_excel': 'Excel',
                'sem_stats_filetype_csv': 'CSV',
                'sem_stats_filetype_all': 'Visi failai',
                'sem_stats_max_files_warning': 'Galima įkelti daugiausiai 10 failų.',
                'sem_stats_status_cleared': 'Išvalyta. Įkelkite failus.',
                'sem_stats_load_errors_title': 'Įkėlimo klaidos',
                'sem_stats_status_loaded': 'Įkelta {num} failų. Tikrinkite stulpelių priskyrimus ir paspauskite PRADĖTI ANALIZĘ.',
                'sem_stats_status_detected': 'Stulpeliai aptikti. Patikrinkite priskyrimus ir paspauskite PRADĖTI ANALIZĘ.',
                'sem_stats_no_files_warning': 'Pirmiausia įkelkite Excel failus.',
                'sem_stats_param_gb_density': 'Grūdelių ribų tankis',
                'sem_stats_param_roughness_macro': 'Paviršiaus šiurkštumas Ra (globalus)',
                'sem_stats_param_fracture': 'Lūžio topologijos indeksas',
                'sem_stats_genitive_diameter': 'ekvivalentinio diametro',
                'sem_stats_genitive_area': 'ploto',
                'sem_stats_genitive_ff': 'sferiškumo',
                'sem_stats_genitive_aspect': 'anizotropijos',
                'sem_stats_genitive_perimeter': 'perimetro',
                'sem_stats_genitive_area_3d': '3D ploto',
                'sem_stats_genitive_roughness': 'Ra šiurkštumo',
                'sem_stats_axis_diameter': 'Ekvivalentinis diametras',
                'sem_stats_axis_area': 'Plotas',
                'sem_stats_axis_ff': 'Sferiškumas',
                'sem_stats_axis_aspect': 'Anizotropija',
                'sem_stats_axis_perimeter': 'Perimetras',
                'sem_stats_axis_area_3d': '3D plotas',
                'sem_stats_axis_roughness': 'Ra šiurkštumas',
                'sem_stats_param_fracture_type': 'Lūžio tipas (vyraujantis)',
                'sem_stats_status_completed': '✅ Analizė baigta ({num} failai). Grūdelių: {micro}. Makro parametrų: {macro}.',
                'sem_stats_tree_hdr_micro': '── MIKRO parametrai (globalus masyvas) ──',
                'sem_stats_tree_hdr_macro': '── MAKRO parametrai (vidurkis per failus) ──',
                'sem_stats_histogram_warning': 'Pirmiausia atlikite analizę (reikalingi diameter arba area duomenys).',
                'sem_stats_histogram_win_title': 'Grūdelių pasiskirstymo analizė',
                'sem_stats_select_param': 'Pasirinkite parametrą: ',
                'sem_stats_peaks_legend': 'Pikai: {peaks} {unit}',
                'sem_stats_mean_legend': 'Vidurkis: {mean:.3f} ± {std:.3f} {unit}',
                'sem_stats_axis_density': 'Tikimybės tankis',
                'sem_stats_plot_title': 'LLTO grūdelių {label} pasiskirstymas (N={num})',
                'sem_stats_radio_diameter': 'Diametras',
                'sem_stats_radio_area': 'Plotas',
                'sem_stats_radio_ff': 'Sferiškumas',
                'sem_stats_radio_aspect': 'Anizotropija',
                'sem_stats_radio_perimeter': 'Perimetras',
                'sem_stats_radio_area_3d': '3D Plotas',
                'sem_stats_radio_roughness': 'Šiurkštumas Ra',
                'sem_stats_no_results_warning': 'Pirmiausia atlikite analizę.',
                'sem_stats_export_title': 'Išsaugoti SEM statistiką',
                'sem_stats_col_mean': 'Vidurkis',
                'sem_stats_col_std': 'Standartinis nuokrypis',
                'sem_stats_col_type': 'Tipas',
                'sem_stats_sheet_stats': 'Statistika',
                'sem_stats_sheet_combined': 'Apjungti_duomenys',
                'sem_stats_export_success_msg': 'Rezultatai sėkmingai išsaugoti:\n{}',
                'sem_stats_export_error_msg': 'Nepavyko išsaugoti failo:\n{}',

                # Arc Width Analysis
                'arc_no_data': 'Pirmiausia užkraukite duomenis!',
                'arc_all_selected': 'Visi pasirinkti',
                'arc_window_title': 'CeraMIS - Lanko pločio analizė (Stačiakampis žymėjimas)',
                'arc_sidebar_title': 'LANKO PLOČIO ANALIZĖ',
                'arc_desc_usage': 'Naudojimas:\n1. Dešiniuoju pelės klavišu apveskite stačiakampį aplink norimą lanką.\n2. Paspauskite [Užrakinti lanką] arba \'S\', kad išsaugotumėte lanką.\n3. Apveskite kitą lanką ir pakartokite.',
                'arc_temp_selection': 'Temperatūros parinkimas:',
                'arc_locked_results_title': 'Užrakinti rezultatai:',
                'arc_no_locked_arcs': 'Nėra užrakintų lankų.\n',
                'arc_no_points_selected': 'Nėra taškų pasirinktame rėžyje!',
                'arc_results_label': 'Rezultatai:\n',
                'arc_and_more_label': '\n... ir dar {}',
                'axis_real_z_norm': "Z', \u03a9\u00b7m",
                'axis_imag_z_norm': "-Z'', \u03a9\u00b7m",
                'arc_plot_instruction': 'Dešiniuoju pelės mygtuku pažymėkite lanką stačiakampiu\nUžrakinti lankai: {}',
                'arc_sidebar_arc_info': 'Lankas #{idx} ({temp} K):\n',
                'arc_please_select_first': 'Pirmiausia pažymėkite lanką stačiakampiu!',
                'arc_locked_success_title': 'Lankas užrakintas sėkmingai! Galite žymėti kitą.\nUžrakinti lankai: {}',
                'arc_no_arcs_export': 'Nėra užrakintų lankų eksportavimui!',
                'arc_export_save_title': 'Išsaugoti lankų analizės rezultatus',
                'arc_excel_sheet_title': 'Lankų rezultatai',
                'arc_col_index': 'Lanko indeksas',
                'arc_col_temp': 'Temperatūra',
                'arc_col_resistance': 'Varža R',
                'arc_col_n': 'CPE rodiklis n',
                'arc_col_q': 'CPE talpa Q',
                'arc_col_ceq': 'Ekvivalentinė talpa C_eq',
                'arc_col_x1': 'Sankirta X1',
                'arc_col_x2': 'Sankirta X2',
                'arc_col_chi2': 'Chi-kvadratas (Chi²)',
                'arc_item_prefix': 'Lankas #{}',
                'arc_export_success': 'Duomenys, suderinami su Origin, sėkmingai eksportuoti į:\n{}',
                'arc_export_error': 'Nepavyko eksportuoti į Excel:\n{}',
                'arc_import_title': 'Importuoti lankų analizės rezultatus',
                'arc_import_structure_error': 'Neteisinga failo struktūra! Nepavyko rasti reikiamų lanko stulpelių.',
                'arc_import_dialog_title': 'Importuoti duomenis',
                'arc_import_confirm_clear': 'Jūs jau turite užrakintų lankų. Ar norite juos išvalyti prieš importuojant?\nPasirinkus „Taip“ – esami bus išvalyti.\nPasirinkus „Ne“ – nauji lankai bus pridėti prie esamų.\nPasirinkus „Atšaukti“ – veiksmas bus nutrauktas.',
                'arc_import_success_msg': 'Sėkmingai importuota {} lankų.',
                'arc_import_error_msg': 'Nepavyko nuskaityti Excel failo:\n{}',
                'arc_lock_btn': '🔒 Užrakinti lanką (S)',
                'arc_clear_btn': '🧹 Išvalyti užrakintus (C)',
                'arc_import_btn': '📂 Importuoti iš Excel',
                'arc_export_btn': '📊 Eksportuoti į Excel',

                # DRT Tab Additions
                'drt_tau_min': 'tau min (s):',
                'drt_tau_max': 'tau max (s):',
                'drt_auto_bounds_placeholder': '(palikite tuščią automatiniam aptikimui)',
                'drt_no_auto_peak': 'Nepavyko automatiškai rasti piko. Įveskite ribas rankiniu būdu.',
                'drt_no_data_in_project': 'Projekte nerasta DRT duomenų.',
                'drt_3d_map_title': '3D DRT žemėlapis',
                'drt_3d_temp_axis': 'Temperatūra, K',
                'drt_3d_gamma_axis': '\u03b3(ln \u03c4), \u03a9',
                'drt_3d_title': 'DRT pasiskirstymas priklausomai nuo temperatūros ir dažnio',
                'drt_analysis_title': 'DRT analizė: {}',

                # 3D Crystal Viewer
                'crystal_view_title': '🔷 LLTO Kristalų Struktūros\n3D Vizualizacija',
                'crystal_phase_label': 'Kristalografinė fazė:',
                'crystal_phase_cubic': 'Kubinė',
                'crystal_phase_tetragonal': 'Tetragoninė',
                'crystal_phase_orthorhombic': 'Ortorombinė',
                'crystal_phase_monoclinic': 'Monoklinė',
                'crystal_phase_twinned': 'Dvynių domenai',
                'crystal_phase_amorphous': 'Amorfinė',
                'crystal_phase_rp': 'Ruddlesden-Popper',
                'crystal_cell_label': 'Gardelės dydis:',
                'crystal_show_boundary': 'Rodyti domenų ribą',
                'crystal_show_windows': 'Rodyti deguonies langus',
                'crystal_show_radii': 'Rodyti joninius spindulius',
                'crystal_stoichiometry': 'Stechiometrija',
                'crystal_apply_btn': 'Taikyti fazę ir stechiometriją',
                'crystal_temp_label': 'Temperatūra: {} K',
                'crystal_tilt_label': 'Oktaedro pasvirimas: {}°',
                'crystal_tilt_format': 'Oktaedro pasvirimas: {}° (Ti-O-Ti: {}°)',
                'crystal_jump_start': '▶ Tęsti / Pradėti Li šuolį',
                'crystal_jump_stop': '⏸ Sustabdyti šuolio animaciją',
                'crystal_jump_field_active': '▶ Įjungti šuolį (Laukas įjungtas)',
                'crystal_no_pairs': 'Nerastos gretimos Li–Vakansijos poros animacijai.',
                'crystal_field_check': 'Įjungti elektrinio lauko poveikį',
                'crystal_field_group': '⚡ Elektrinis laukas',
                'crystal_white_bg': 'Baltas fonas',
                'crystal_export_png': '📷 Eksportuoti PNG',
                'crystal_save_png_title': 'Saugoti PNG',
                'crystal_png_filetype': 'PNG paveikslėlis (*.png)',
                'crystal_domain_boundary_label': 'Domenų riba',
                'crystal_atom_La': 'La',
                'crystal_atom_Li': 'Li',
                'crystal_atom_Ti': 'Ti',
                'crystal_atom_O': 'O',
                'crystal_atom_Vac': 'Vakansija',

                # Meta-data & Graph keys
                'meta_z_real_f': "Varžos realioji dalis Z' vs f",
                'meta_z_imag_f': "-Varžos tariamoji dalis -Z'' vs f",
                'meta_eps_real_f': "Skvarbos realioji dalis \u03b5' vs f",
                'meta_eps_imag_f': "Skvarbos tariamoji dalis \u03b5'' vs f",
                'meta_sigma_f': "Laidumo realioji dalis \u03c3' vs f",
                'meta_m_imag_f': "Modulio tariamoji dalis M'' vs f",
                'meta_tan_delta_f': "Nuostolių tangentas tan \u03b4 vs f",
                'meta_z_real_imag_f': "Reali ir tariama varža vs f",
                'meta_z_real_imag_label': "Reali Z' ir tariama -Z''",
                'meta_abs_z_f': "Varžos modulis |Z| vs f",
                'plot_open_error': "Klaida atidarant grafiką: {}",
                'label_temp_k': "Temperatūra (K)",
                'title_edit_export_graph': "Grafiko duomenų redagavimas ir eksportas",
                'btn_updated_success': "Grafiko nustatymai sėkmingai atnaujinti!",
                'btn_update': "🔄 Atnaujinti grafiką",
                'title_export_graph': "Eksportuoti grafiko duomenis",
                'btn_exported_success': "Duomenys sėkmingai eksportuoti!",
                'btn_export_dots': "📊 Eksportuoti taškus į Excel",
                'btn_copied_success': "Duomenys sėkmingai nukopijuoti į iškarpinę!",
                'btn_copy_clipboard': "📋 Kopijuoti į iškarpinę",
                'label_none': "Nėra",
                'btn_plot': "📈 Braižyti",

                # 3D PyVista Plot Titles
                'title_3d_nyquist_bode_spiral': "3D Naikvisto-Bodė spiralė",
                'title_nyquist_evolution': "Naikvisto evoliucija",
                'title_cole_cole_3d': "Cole-Cole 3D (\u03b5' vs \u03b5'' vs T)",
                'title_phase_angle_3d': "Fazės kampo 3D (-\u0398)",
                'title_3d_ac_conductivity': "3D Kintamosios Srovės Laidumas",
                'title_electric_modulus_surface': "Elektrinio Modulio Paviršius (M'')",
                'title_pseudo_drt_relief': "Pseudo-DRT Temperatūrinis Reljefas",
                'title_conductivity_map': "Laidumo Žemėlapis (1000/T)",
                'title_norm_z_surface': "Normalizuotas Z'' paviršius",
                'title_norm_m_surface': "Normalizuotas M'' paviršius",

                # SAM interactive UI keys
                'sam_palette': "Spalvų paletė:",
                'sam_smooth': "Ribų glotninimas:",
                'sam_height': "Reljefo aukščio mastelis:",
                'sam_opacity': "3D tinklelio nepermatomumas:",
                'sam_btn_update': "🔄 Atnaujinti 3D modelį",
                'sam_status_calc': "Grūdelių statistika: {num} grūdeliai, ribų tankis = {density:.4f} \u00b5m\u207b\u00b9, Ra = {ra:.2f} nm, Lūžio indeksas = {frac:.3f}",
                'sam_btn_save_png': "📷 Saugoti 3D vaizdą kaip PNG",
                'sam_btn_export_xlsx': "📊 Eksportuoti grūdelių duomenis į Excel",
                'sam_btn_repeat': "🔄 Perskaičiuoti statistiką",
                'sam_btn_roi': "✂ Keisti apdorojimo sritį (ROI)",
                'sam_btn_save_png_short': "📷 Saugoti PNG",
                'sam_status_found': "Rasta {num} grūdelių",
                'sam_manual_header': "🔬 SEM AI Rankinio matavimo režimas",
                'sam_lbl_param': "Parametras",
                'sam_lbl_val': "Vertė",

                # Arrhenius ir išdėstymo trūkstami raktai
                'arr_status_waiting': "Laukiama projekto...",
                'arr_load_proj_placeholder': "(įkelti projektą)",
                'arr_click_point_info': "Paspauskite ant taško detalesnei informacijai",
                'arr_browse_btn': "Naršyti...",
                'arr_fit_select_title': "Modeliavimo rezultatų parinkimas",
                'arr_fit_last': "Paskutinis",
                'arr_fit_first': "Pirmasis",
                'arr_fit_index_label': "Pagal indeksą:",
                'arr_select_proj_title': "Pasirinkite dearEIS projektą",
                'arr_proj_filetype': "dearEIS projektas",
                'filetype_all': "Visi failai",
                'arr_proj_loaded': "Projektas įkeltas. Datasetai: {}",
                'arr_no_fits': "(nėra derinamų modelių rezultatų)",
                'arr_and_more': "  ... ir dar {}",
                'arr_fit_results_header': "Derinimo rezultatai (pirmasis datasetas):\n",
                'arr_proj_loaded_auto': "Projektas įkeltas automatiškai. Datasetai: {}",
                'arr_select_point_or_reg': "Pasirinkite tašką arba regresiją",
                'arr_invalid_temp': "Neteisinga temperatūra",
                'invalid_geometry': "Neteisingi geometrijos duomenys pagrindiniame lange.",
                'arr_no_data_found': "Tinkamų duomenų nerasta.",
                'arr_plot_title_r': "Arenijaus grafikas ($R$=$R_{t}$+$R_{gr}$)",
                'arr_plot_title_prefix': "Arenijaus grafikas",
                'arr_analysis_title': "Arenijaus analizė",
                'arr_regression_label': "Regresija:",
                'arr_plot_title_formula': "Arenijaus grafikas",
                'arr_instructions': "🖱️ Pele apveskite stačiakampį (kairiu/dešiniu klavišu) taškams pažymėti/atžymėti. 🎯 Spauskite ant taško informacijai.",
                'arr_plot_ready': "Grafikas paruoštas. Taškai: {}",
                'arr_current_pts': "Dabartinis",
                'arr_select_pts_for_reg': "(pasirinkite taškus regresijai)",
                'arr_need_2_points': "Reikia bent 2 pasirinktų taškų regresijos tiesei išsaugoti.",
                'arr_source_data_point': "Duomenų taškas",
                'arr_source_line': "Tiesė",
                'arr_source_active': "Aktyvi regresija",
                'arr_point_label': "Taškas",
                'arr_selected_point_status': "Pasirinktas taškas {temp_k:.1f} K ({source}). {name} = {val} {unit} | \u03c3 = {sigma} S/cm",
                'arr_all_deselected': "Visi taškai atžymėti.",
                'arr_original_file_missing': "Originalus projekto failas nerastas.",
                'arr_proj_updated_saved': "Projektas sėkmingai atnaujintas ir išsaugotas.",
                'arr_error_saving_proj': "Klaida išsaugant projektą:\n{}",
                'arr_save_csv_title': "Išsaugoti CSV",
                'arr_csv_filetype': "CSV failas",
                'arr_csv_saved': "CSV failas išsaugotas:\n{}",
                'drt_results_placeholder': "(pasirinkite datasetą ir rėžius)",
                'filetype_supported': "Palaikomi failai",
                'filetype_txt': "Tekstiniai failai",
                'filetype_zview': "ZView failai",
                'filetype_excel': "Excel failai",
                'sem_settings_title': "SEM AI Nustatymai",
                'sam_model_version_label': "SAM modelio versija:",
                'sam_window_title_3d': "SAM 3D Reljefas - Interaktyvi Analizė",
                'sam_window_title_manual': "SAM Rankinis Koregavimas",
                'sam_scale_win_title': "Mastelis",
                'sam_units_vnt': "vnt.",
                'sam_scale_prompt': "Įveskite pažymėtos mastelio linijos ilgį mikrometrais (µm):",
                'sam_step1_title': "ŽINGSNIS 1: Nustatykite mastelį!\nSpustelkite ant mastelio linijos pradžios, o po to – ant pabaigos.",
                'sam_step2_title': "ŽINGSNIS 2: Pasirinkite apdorojimo sritį!\nApveskite su pele norimą sritį.\nPaspauskite 'Enter', kai baigsite.",
                'sam_manual_title_format': "Apdorotoje srityje rasta grūdelių: {len_masks}",
                'sam_manual_info_bar': "RANKINIS APDOROJIMAS  |  [J] Sujungti  |  [D] Ištrinti  |  [S] Perskirti  |  [ESC] Baigti",
                'sam_select_image_title': "Pasirinkite SEM nuotrauką analizei",
                'sam_image_filetype_desc': "Nuotraukos",
                'sam_merge_warning': "Pasirinkite bent 2 grūdelius sujungimui!",
                'sam_split_prompt': "Perskiriamas grūdelis {idx}. Pažymėkite du taškus centre naujų dalių.",
                'sam_export_grain_sheet': "Grūdelių parametrai",
                'sam_stats_calculated': "Suskaičiuoti parametrai:",
                'sam_export_success': "Parametrai sėkmingai eksportuoti!",
                'sam_export_error': "Nepavyko eksportuoti parametrų!",
                'sam_stat_algorithm': "Algoritmas",
                'sam_stat_count': "Grūdelių skaičius",
                'sam_stat_mean_diam': "Vid. diametras",
                'sam_stat_min_diam': "Min diametras",
                'sam_stat_max_diam': "Max diametras",
                'sam_stat_mean_area': "Vid. plotas",
                'sam_stat_min_area': "Min plotas",
                'sam_stat_max_area': "Max plotas",
                'sam_stat_sphericity': "Vid. sferiškumas",
                'sam_stat_aspect': "Vid. anizotropija",
                'sam_stat_gb_density': "Ribų tankis",
                'sam_stat_roughness': "Vid. Ra",
                'sam_stat_fracture_idx': "Lūžio indeksas",
                'sam_stat_fracture_type': "Lūžio tipas",
                'fracture_Stipriai_Intergranuliarinis': "Stipriai Intergranuliarinis",
                'fracture_Transgranuliarinis': "Transgranuliarinis",
                'fracture_Mišrus': "Mišrus",
                'script_not_found': "Failas {} nerastas.",
                'axis_log_f': "log(f), Hz",
                'axis_real_eps_unit': "ε', vnt.",
                'axis_imag_eps_unit': "ε'', vnt.",
                'axis_phase_angle_short': "-Θ, °",
                'axis_conductivity_surface': "log(σ'), S/m",
                'axis_imag_m_unit': "M'', vnt.",
                'axis_pseudo_drt_value': "-dZ'/d(log f)",
                'axis_inv_temp': "1000/T, K⁻¹",
                'axis_norm_z_spec': "Z''/Z''max",
                'axis_norm_m_spec': "M''/M''max",
                'sam_status_recalculating': "⏳ Perskaičiuojama, prašome palaukti...",
                'sam_excel_stat_mean': "Vidurkis",
                'sam_excel_stat_min': "Minimum",
                'sam_excel_stat_max': "Maximum",
                'sam_excel_stat_std': "Std. nuokrypis",
                'sam_excel_param': "Parametras",
                'sam_excel_value': "Reikšmė",
                'sam_excel_sheet': "Analizė",
                'sam_stat_mean_diam_col': "Vidurkis",
                'sam_opac_percent': "Skaidrumas: {}%",
                'sam_smooth_iter': "{} iter.",
                'sam_height_x': "{:.1f}x",
                'sam_open_3d_msg': "Atidaromas 3D langas! Jį galite sukioti su pele, priartinti su ratuku."
            }
        }

    def load_config(self):
        if os.path.exists(self.config_file):
            try:
                self.config.read(self.config_file, encoding='utf-8')
                self.lang = self.config.get('Settings', 'language', fallback='lt').lower()
            except Exception as e:
                print(f"Error reading config file: {e}")
                self.create_default_config()
        else:
            self.create_default_config()

    def create_default_config(self):
        self.config['Settings'] = {
            'language': 'lt',
            'default_spectrum_file': r"C:\Users\bigma\OneDrive\BAKALAURAS fiz\4 KURSAS\Bakalauras\rezultatai\LLTO 145K - 1060K temperatūros 1Hz - 9Ghz spektre.xlsx",
            'default_deareis_project': r"C:\Users\bigma\OneDrive\BAKALAURAS fiz\4 KURSAS\Bakalauras\rezultatai\dearEIS LLTO nuo 145k iki 1060K.json",
            'default_thickness': '1.5',
            'default_area': '0.51',
            'default_normalized': 'True',
            'author': 'Mantas Jonas Marcinkevičius',
            'gui_scale': '1.0',
            'sam3_model_path': 'sam3.1_multiplex.pt',
            'sam2_model_path': 'sam2.1_hiera_large.pt',
            'default_sem_folder': '',
            'default_sem_stats_folder': ''
        }
        try:
            with open(self.config_file, 'w', encoding='utf-8') as configfile:
                self.config.write(configfile)
        except Exception as e:
            print(f"Error creating default config file: {e}")
        self.lang = 'lt'

    def get(self, key, default=None):
        lang_trans = self.translations.get(self.lang, self.translations['en'])
        return lang_trans.get(key, default if default is not None else key)

    def get_config_val(self, option, fallback=None):
        return self.config.get('Settings', option, fallback=fallback)

    def get_config_bool(self, option, fallback=False):
        return self.config.getboolean('Settings', option, fallback=fallback)

    def set_config_val(self, option, value):
        self.config.set('Settings', option, str(value))
        try:
            with open(self.config_file, 'w', encoding='utf-8') as configfile:
                self.config.write(configfile)
        except Exception as e:
            print(f"Error writing to config file: {e}")

_translator = TranslationManager()

def _(key, default=None):
    return _translator.get(key, default)

def get_config_val(option, fallback=None):
    return _translator.get_config_val(option, fallback=fallback)

def get_config_bool(option, fallback=False):
    return _translator.get_config_bool(option, fallback=fallback)

def set_config_val(option, value):
    _translator.set_config_val(option, value)
